// Auth
export const LOGIN_SUCCESS = '@LOGIN_SUCCESS';
export const LOGIN_FAILED = '@LOGIN_FAILED';
export const REGISTER_SUCCESS = '@REGISTER_SUCCESS';
export const REGISTER_FAILED = '@REGISTER_FAILED';
export const LOGOUT = '@LOGOUT';

// Profile
export const GET_USER_SUCCESS = '@GET_USER_SUCCESS';
export const GET_USER_FAILED = '@GET_USER_FAILED';
export const UPDATE_USER_SUCCESS = '@UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = '@UPDATE_USER_FAILED';

// Setting
export const UPDATE_PASSWORD_SUCCESS = '@UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = '@UPDATE_PASSWORD_FAILED';

// Global
export const SET_LOADING = '@SET_LOADING';
export const REFRESH = '@REFRESH';
export const SET_NOTIF = '@SET_NOTIF';

// HOME
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';
export const GET_DETAIL_PRODUCT_FAIL = 'GET_DETAIL_PRODUCT_FAIL';
export const GET_DETAIL_PRODUCT_LOADING = 'GET_DETAIL_PRODUCT_LOADING';

// Seller
export const GET_CATEGORY_SUCCESS = '@GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILED = '@GET_CATEGORY_FAILED';

// Seller Product
export const ADD_PRODUCT_SUCCESS = '@ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = '@ADD_PRODUCT_FAILED';

export const GET_PRODUCTSELLER_SUCCESS = '@GET_PRODUCTSELLER_SUCCESS';
export const GET_PRODUCTSELLER_FAILED = '@GET_PRODUCTSELLER_FAILED';
export const GET_PRODUCTSELLER_LOADING = '@GET_PRODUCTSELLER_LOADING';

export const GET_ORDERSELLER_SUCCESS = '@GET_ORDERSELLER_SUCCESS';
export const GET_ORDERDETAILSELLER_SUCCESS = '@GET_ORDERDETAILSELLER_SUCCESS';
export const GET_ORDERSELLER_FAILED = '@GET_ORDERSELLER_FAILED';
export const GET_ORDERSELLER_LOADING = '@GET_ORDERSELLER_LOADING';

export const GET_DETAIL_SELLER_SUCCESS = '@GET_DETAIL_SELLER_SUCCESS ';
export const GET_DETAIL_SELLER_FAILED = '@GET_DETAIL_SELLER_FAILED';
export const GET_DETAIL_SELLER_LOADING = '@GET_DETAIL_SELLER_LOADING';

export const UPDATE_PRODUCT_SUCCESS = '@UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = '@UPDATE_PRODUCT_FAILED';

export const DELETE_PRODUCT_SUCCESS = '@DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = '@DELETE_PRODUCT_FAILED';

// Seller Order
export const UPDATE_ORDER_SUCCESS = '@UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_LOADING = '@UPDATE_ORDER_SUCCESS';


// Buyer
export const BID_SUCCESS = '@BID_SUCCESS';
export const BID_FAILED = '@BID_FAILED';

export const GET_BUYER_ORDER_SUCCESS = '@GET_BUYER_ORDER_SUCCESS';
export const GET_DETAIL_BUYER_ORDER_SUCCESS = '@GET_DETAIL_BUYER_ORDER_SUCCESS';
export const GET_BUYER_ORDER_FAILED = '@GET_BUYER_ORDER_FAILED';
export const BUYER_ORDER_LOADING = '@GET_BUYER_LOADING';

// Banner
export const SET_BANNER = '@@@SET_BANNER';

// History
export const GET_HISTORY_SUCCESS = '@GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAILED = '@GET_HISTORY_FAILED';
export const GET_HISTORY_LOADING = '@GET_HISTORY_LOADING';

export const GET_ID_HISTORY_SUCCESS = '@GET_ID_HISTORY_SUCCESS';
export const GET_ID_HISTORY_FAILED = '@GET_ID_HISTORY_FAILED';
export const GET_ID_HISTORY_LOADING = '@GET_ID_HISTORY_LOADING';
